import { defineConfig } from "vitest/config";
import { PLATFORM_QUALIFICATION_TEST_FILES } from "./vitest.tiers.mjs";

/**
 * The platform-qualification tier: the frozen Phase 01-05 gates that need evidence a clean checkout
 * does not have.
 *
 * This tier is NOT a skip and NOT a demotion. Every file here is still executed, still asserts exactly
 * what it asserted before, and still fails closed — it is executed by `Platform Qualification`
 * (`.github/workflows/platform-qualification.yml`, `workflow_dispatch`) after the prerequisites those
 * suites declare have been generated by their own official generators. What changed is only WHO runs
 * them and WHEN, which is the honest answer to a measured fact: on a hosted push runner the Phase 04
 * lifecycle gate saw a 56-file corpus against an invariant of over 1000 files, and the Phase 05
 * certificate read artifacts no step had produced. Those are properties of the RUN, not defects in the
 * suites, so the fix is to run them in a run that has the evidence.
 *
 * The alternative — making them skip when the evidence is absent — is the failure mode the postbuild
 * config already names: it turns "we verified this" into "we did not look". So nothing here is
 * conditional, `process.env.CI` appears nowhere in it, and `pnpm test` / `pnpm run test:postbuild`
 * remain what a clean push runner can honestly satisfy on its own.
 *
 * The per-test ceiling is raised above the postbuild tier's 60s because the Phase 04 generator stats a
 * corpus that reaches tens of thousands of files on a real host. A ceiling is not a gate: raising it
 * cannot let a weaker assertion pass, and the invariants inside the suites are untouched.
 */
export default defineConfig({
  test: {
    environment: "node",
    include: PLATFORM_QUALIFICATION_TEST_FILES,
    testTimeout: 120000
  }
});
