import { contextBridge, ipcRenderer } from "electron";
import type { AppSnapshot, BossBridge, CreateConversationInput, CreateTaskInput, CustomProviderInput, ProviderId, TaskStatus, UpdateApiSettingInput, UpdateRemoteChannelInput, ViewBounds } from "../src/shared/contracts";

const bridge: BossBridge = {
  snapshot: () => ipcRenderer.invoke("boss:snapshot"),
  progress: () => ipcRenderer.invoke("boss:progress"),
  ownerDashboard: () => ipcRenderer.invoke("boss:owner-dashboard"),
  activeIntervention: (taskId: string) => ipcRenderer.invoke("boss:active-intervention", taskId),
  listInterventions: (taskId?: string) => ipcRenderer.invoke("boss:list-interventions", taskId),
  resolveIntervention: (taskId: string, kind: import("../src/shared/intervention").InterventionKind, answer: string) => ipcRenderer.invoke("boss:resolve-intervention", taskId, kind, answer),
  researchStart: (input: { id?: string; researchQuestion?: string; goal?: string; workspace: string; reviewers: string[]; autonomy?: "AUTOPILOT" | "GUIDED"; hypothesis?: string; providerPolicy?: "AUTO" | "FIXED"; maxExperiments?: number; maxSteps?: number; maxProviderCalls?: number }) => ipcRenderer.invoke("boss:research-start", input),
  researchStatus: (id: string) => ipcRenderer.invoke("boss:research-status", id),
  researchList: () => ipcRenderer.invoke("boss:research-list"),
  researchStep: (id: string) => ipcRenderer.invoke("boss:research-step", id),
  researchAutopilot: (id: string, maxSteps?: number) => ipcRenderer.invoke("boss:research-autopilot", id, maxSteps),
  researchCompilePdf: (id: string) => ipcRenderer.invoke("boss:research-compile-pdf", id),
  researchResume: (id: string) => ipcRenderer.invoke("boss:research-resume", id),
  researchWait: (input: { id: string; kind: import("../src/shared/intervention").InterventionKind; question: string; options?: string[]; blockingStepId: string; contextSummary?: string }) => ipcRenderer.invoke("boss:research-wait", input),
  researchProtocolFreeze: (id: string, protocol: import("../src/shared/research-protocol").ResearchProtocol) => ipcRenderer.invoke("boss:research-protocol-freeze", id, protocol),
  pickAttachments: (conversationId: string) => ipcRenderer.invoke("boss:pick-attachments", conversationId),
  addAttachmentBytes: (input: { conversationId: string; originalName: string; mime?: string; bytes: Uint8Array }) => ipcRenderer.invoke("boss:add-attachment-bytes", input),
  removeAttachment: (conversationId: string, inputObjectId: string) => ipcRenderer.invoke("boss:remove-attachment", conversationId, inputObjectId),
  attachmentPath: (conversationId: string, inputObjectId: string) => ipcRenderer.invoke("boss:attachment-path", conversationId, inputObjectId),
  createTask: (input: CreateTaskInput) => ipcRenderer.invoke("boss:create-task", input),
  dispatchTask: (input: CreateTaskInput) => ipcRenderer.invoke("boss:dispatch-task", input),
  resolveModeProposal: (taskId: string, approveWork: boolean) => ipcRenderer.invoke("boss:resolve-mode-proposal", taskId, approveWork),
  updateApiSetting: (input: UpdateApiSettingInput) => ipcRenderer.invoke("boss:update-api-setting", input),
  updateRemoteChannel: (input: UpdateRemoteChannelInput) => ipcRenderer.invoke("boss:update-remote-channel", input),
  updateRuntimeControl: (runtimeId: string, enabled: boolean, priority: number) => ipcRenderer.invoke("boss:update-runtime-control", runtimeId, enabled, priority),
  updateRoleRoute: (role, runtimeIds, fallback) => ipcRenderer.invoke("boss:update-role-route", role, runtimeIds, fallback),
  loadRemoteCommand: (commandId: string) => ipcRenderer.invoke("boss:load-remote-command", commandId),
  dismissRemoteCommand: (commandId: string) => ipcRenderer.invoke("boss:dismiss-remote-command", commandId),
  createFolder: (name: string) => ipcRenderer.invoke("boss:create-folder", name),
  renameFolder: (folderId: string, name: string) => ipcRenderer.invoke("boss:rename-folder", folderId, name),
  createConversation: (input: CreateConversationInput) => ipcRenderer.invoke("boss:create-conversation", input),
  renameConversation: (conversationId: string, title: string) => ipcRenderer.invoke("boss:rename-conversation", conversationId, title),
  moveConversation: (conversationId: string, folderId: string) => ipcRenderer.invoke("boss:move-conversation", conversationId, folderId),
  selectConversation: (conversationId: string) => ipcRenderer.invoke("boss:select-conversation", conversationId),
  archiveConversation: (conversationId: string, archived: boolean) => ipcRenderer.invoke("boss:archive-conversation", conversationId, archived),
  deleteConversation: (conversationId: string, userConfirmed: boolean) => ipcRenderer.invoke("boss:delete-conversation", conversationId, userConfirmed),
  deleteConversations: (conversationIds: string[], userConfirmed: boolean) => ipcRenderer.invoke("boss:delete-conversations", conversationIds, userConfirmed),
  duplicateConversation: (conversationId: string) => ipcRenderer.invoke("boss:duplicate-conversation", conversationId),
  exportConversation: (conversationId: string) => ipcRenderer.invoke("boss:export-conversation", conversationId),
  addCustomProvider: (input: CustomProviderInput) => ipcRenderer.invoke("boss:add-custom-provider", input),
  removeCustomProvider: (providerId: ProviderId) => ipcRenderer.invoke("boss:remove-custom-provider", providerId),
  launchTask: (taskId: string) => ipcRenderer.invoke("boss:launch-task", taskId),
  prepareTask: (taskId: string) => ipcRenderer.invoke("boss:prepare-task", taskId),
  sendTask: (taskId: string) => ipcRenderer.invoke("boss:send-task", taskId),
  captureTask: (taskId: string) => ipcRenderer.invoke("boss:capture-task", taskId),
  releaseReview: (taskId: string) => ipcRenderer.invoke("boss:release-review", taskId),
  advanceCouncil: (taskId: string) => ipcRenderer.invoke("boss:advance-council", taskId),
  buildEvidence: (taskId: string) => ipcRenderer.invoke("boss:build-evidence", taskId),
  acceptEvidence: (taskId: string) => ipcRenderer.invoke("boss:accept-evidence", taskId),
  externalSessionList: () => ipcRenderer.invoke("boss:external-session-list"),
  externalArchiveRun: () => ipcRenderer.invoke("boss:external-archive-run"),
  engineeringGoalStatus: () => ipcRenderer.invoke("boss:engineering-goal-status"),
  engineeringGoalRun: (input: import("../src/shared/contracts").EngineeringGoalRunInput) => ipcRenderer.invoke("boss:engineering-goal-run", input),
  rehydrateEvidence: (taskId: string) => ipcRenderer.invoke("boss:rehydrate-evidence", taskId),
  runCodexReview: (taskId: string) => ipcRenderer.invoke("boss:run-codex-review", taskId),
  openProvider: (providerId: ProviderId) => ipcRenderer.invoke("boss:open-provider", providerId),
  closeProvider: (providerId: ProviderId) => ipcRenderer.invoke("boss:close-provider", providerId),
  layoutViews: (layout: Partial<Record<ProviderId, ViewBounds>>) => ipcRenderer.invoke("boss:layout-views", layout),
  setProviderViewsVisible: (visible: boolean) => ipcRenderer.invoke("boss:set-provider-views-visible", visible),
  setProviderZoom: (providerId: string, factor: number) => ipcRenderer.invoke("boss:set-provider-zoom", providerId, factor),
  reloadProvider: (providerId: string) => ipcRenderer.invoke("boss:reload-provider", providerId),
  setWorkspaceView: (view: "MERGED" | "DETACHED") => ipcRenderer.invoke("boss:set-workspace-view", view),
  getWorkspaceView: () => ipcRenderer.invoke("boss:get-workspace-view"),
  getWindowState: () => ipcRenderer.invoke("boss:get-window-state"),
  updateTask: (taskId: string, status: TaskStatus) => ipcRenderer.invoke("boss:update-task", taskId, status),
  projectState: (workspaceId?: string) => ipcRenderer.invoke("boss:project-state", workspaceId),
  onSnapshot: (listener: (snapshot: AppSnapshot) => void) => {
    const wrapped = (_event: Electron.IpcRendererEvent, snapshot: AppSnapshot) => listener(snapshot);
    ipcRenderer.on("boss:snapshot-updated", wrapped);
    return () => ipcRenderer.removeListener("boss:snapshot-updated", wrapped);
  }
};

contextBridge.exposeInMainWorld("boss", bridge);
