const fs=require("node:fs"),path=require("node:path"),{randomUUID}=require("node:crypto");
const {app,BrowserWindow}=require("electron");
const {StateStore,providerSeed}=require("../dist-electron/electron/store");
const {ProviderViews}=require("../dist-electron/electron/provider-views");
const {AccountSessionManager}=require("../dist-electron/electron/account-sessions");
const {providerVisionSurface}=require("../dist-electron/electron/computer/backends/provider-vision-surface");
const {MainCommander}=require("../dist-electron/electron/commander/main-commander");
const {TaskLedger}=require("../dist-electron/electron/commander/task-ledger");
const {RuntimeRegistry}=require("../dist-electron/electron/commander/runtime-registry");
const {BudgetManager}=require("../dist-electron/electron/commander/budget-manager");
const {RoleRouter}=require("../dist-electron/electron/commander/role-router");
const {Scheduler}=require("../dist-electron/electron/commander/scheduler");
const {ContextManager}=require("../dist-electron/electron/commander/context-manager");
const {ExecutionGate}=require("../dist-electron/electron/commander/execution-gate");
const root=path.resolve(__dirname,"..","artifacts","vision-"+randomUUID());fs.mkdirSync(root,{recursive:true});
app.setPath("userData",root);app.setPath("sessionData",path.join(root,"sessions"));
let host,views,failDom=false;const evidence={kind:"CONTROLLED_ELECTRON_VISION",root,status:"RUNNING"};
(async()=>{
 await app.whenReady();
 const store=new StateStore(path.join(root,"state.json"));
 host=new BrowserWindow({width:850,height:550,title:"Codex Boss visual acceptance"});
 views=new ProviderViews(host,()=>{},new AccountSessionManager(store),()=>{throw Error("No downloads")});
 const provider=providerSeed[0],view=views.open(provider,false);view.setBounds({x:0,y:0,width:850,height:500});
 const html='<html><head><title>BOSS_STRUCTURED_BROWSER</title></head><body style="margin:0"><canvas width="850" height="500"></canvas><script>const c=document.querySelector("canvas"),g=c.getContext("2d");window.clicks=0;function draw(text){g.fillStyle="white";g.fillRect(0,0,850,500);g.strokeStyle="black";g.strokeRect(40,50,500,120);g.fillStyle="black";g.font="32px Arial";g.fillText(text,65,120);}draw("APPLY CHANGE");c.onclick=e=>{if(e.offsetX>=40&&e.offsetX<=540&&e.offsetY>=50&&e.offsetY<=170){window.clicks++;draw("CHANGE VERIFIED");}};</script></body></html>';
 await view.webContents.loadURL("data:text/html;charset=utf-8,"+encodeURIComponent(html));host.focus();view.webContents.focus();await new Promise(r=>setTimeout(r,300));
 const registry=new RuntimeRegistry(),budgets=new BudgetManager(),ledger=new TaskLedger(path.join(root,".boss","tasks"));
 const commander=new MainCommander(store,registry,new Scheduler(),new RoleRouter(registry,budgets),budgets,new ContextManager(),new ExecutionGate(),ledger,undefined,undefined,{visionSurface:providerVisionSurface(()=>views,path.join(root,"frames")),readBrowser:async id=>{if(failDom)throw Error("Controlled DOM read failure");if(id!==provider.id)throw Error("Unexpected provider");return view.webContents.executeJavaScript("JSON.stringify({url:location.href,title:document.title,text:document.body.innerText})")}});
 const action={name:"click_control",target:'vision:{"surfaceId":"provider:chatgpt","text":"APPLY CHANGE"}',expected:"CHANGE VERIFIED",timeoutMs:20000};
 const task=commander.createTask({title:"Visual canvas action",objective:"desktop "+JSON.stringify(action),providerIds:[]});
 await commander.executeDeterministic(task.id,root);
 const clicks=await view.webContents.executeJavaScript("window.clicks");
 const artifact=store.snapshot().artifacts.find(item=>item.taskId===task.id);
 if(clicks!==1||!artifact?.content.includes('"backend":"vision"')||!artifact.content.includes("CHANGE VERIFIED"))throw Error("Visual action did not produce verified evidence");
 evidence.status="PASS";evidence.clicks=clicks;evidence.taskId=task.id;evidence.result=JSON.parse(artifact.content);evidence.modelCalls=ledger.load(task.id).usage.modelCalls;
 const browserTask=commander.createTask({title:"Structured browser read",objective:"查看网页状态 chatgpt",providerIds:[]});
 await commander.executeDeterministic(browserTask.id,root);
 const browser=store.snapshot().artifacts.find(item=>item.taskId===browserTask.id);
 if(!browser?.content.includes("BOSS_STRUCTURED_BROWSER")||!browser.content.includes('"backend":"structured"'))throw Error("Structured browser read failed");
 evidence.structuredBrowser=JSON.parse(browser.content);
 failDom=true;const fallbackTask=commander.createTask({title:"Automatic OCR fallback",objective:"查看网页状态 chatgpt",providerIds:[]});
 await commander.executeDeterministic(fallbackTask.id,root);
 const fallback=store.snapshot().artifacts.find(item=>item.taskId===fallbackTask.id);
 if(!fallback?.content.includes('"backend":"vision"')||!fallback.content.includes("CHANGE VERIFIED"))throw Error("Automatic OCR fallback failed");
 evidence.automaticFallback=JSON.parse(fallback.content);
})().catch(error=>{evidence.status="FAILED";evidence.error=String(error)}).finally(()=>{views?.destroyAll();host?.destroy();fs.writeFileSync(path.join(root,"result.json"),JSON.stringify(evidence,null,2));app.exit(evidence.status==="PASS"?0:1)});
setTimeout(()=>{if(evidence.status==="RUNNING"){evidence.status="FAILED";evidence.error="Timeout";fs.writeFileSync(path.join(root,"result.json"),JSON.stringify(evidence,null,2));app.exit(1)}},30000).unref();
